using MailKit.Security;
using MimeKit;
using NEO.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace NEO.Core.Services
{
    public class EmailAlertService
    {
        private readonly string _smtpHost;
        private readonly int _smtpPort;
        private readonly string _fromEmail;
        private readonly string _fromPassword;
        private readonly string _toEmail;

        public EmailAlertService(
            string smtpHost,
            int smtpPort,
            string fromEmail,
            string fromPassword,
            string toEmail)
        {
            _smtpHost = smtpHost;
            _smtpPort = smtpPort;
            _fromEmail = fromEmail;
            _fromPassword = fromPassword;
            _toEmail = toEmail;
        }

        // =============================================
        // SEND DAILY TRADE SIGNAL EMAIL
        // =============================================
        public async Task SendDailySignalAsync(
            string runId,
            DateTime businessDate,
            List<string> selectedSectors,
            List<TradeSignal> signals)
        {
            Console.WriteLine("\n🔵 STAGE 9 — Email Alert...");
            Console.WriteLine($"   → Sending to: {_toEmail}");

            try
            {
                var subject = $"📈 ProjectNEO Signals — {businessDate:dd MMM yyyy}";
                var body = BuildEmailBody(runId, businessDate,
                                             selectedSectors, signals);

                using var client = new System.Net.Mail.SmtpClient(_smtpHost, _smtpPort)
                {
                    Credentials = new NetworkCredential(_fromEmail, _fromPassword),
                    EnableSsl = true
                };

                var mail = new MailMessage
                {
                    From = new MailAddress(_fromEmail, "ProjectNEO"),
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                };
                mail.To.Add(_toEmail);

                await client.SendMailAsync(mail);

                Console.WriteLine("   ✅ Email sent successfully!");
                Console.WriteLine("✅ STAGE 9 COMPLETE");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"   ⚠️ Email failed: {ex.Message}");
                Console.WriteLine("   → Pipeline continues without email");
            }
        }

        // =============================================
        // BUILD HTML EMAIL BODY
        // =============================================
        private string BuildEmailBody(
            string runId,
            DateTime businessDate,
            List<string> selectedSectors,
            List<TradeSignal> signals)
        {
            var buys = signals.Where(s => s.Signal == "BUY").ToList();
            var watches = signals.Where(s => s.Signal == "WATCH").ToList();
            var skips = signals.Where(s => s.Signal == "SKIP").ToList();

            var html = $@"
<!DOCTYPE html>
<html>
<body style='font-family: Arial, sans-serif; max-width: 700px; margin: auto;'>

  <h2 style='background:#1a1a2e; color:white; padding:15px; border-radius:8px;'>
    📈 ProjectNEO — Daily Trade Signals
  </h2>

  <p style='color:#555;'>
    <strong>Run ID:</strong> {runId}<br/>
    <strong>Date:</strong> {businessDate:dddd, dd MMMM yyyy}
  </p>

  <h3 style='color:#1a1a2e;'>🎯 Selected Sectors</h3>
  <ul>
    {string.Join("", selectedSectors.Select(s =>
        $"<li style='font-size:16px;'><strong>{s}</strong></li>"))}
  </ul>

  <h3 style='color:#27ae60;'>🟢 BUY Signals ({buys.Count})</h3>
  {BuildSignalTable(buys, "#27ae60")}

  <h3 style='color:#f39c12;'>🟡 WATCH Signals ({watches.Count})</h3>
  {BuildSignalTable(watches, "#f39c12")}

  {(skips.Count > 0 ? $@"
  <h3 style='color:#e74c3c;'>🔴 SKIP Signals ({skips.Count})</h3>
  {BuildSignalTable(skips, "#e74c3c")}" : "")}

  <hr/>
  <p style='color:#aaa; font-size:12px;'>
    Generated by ProjectNEO • {DateTime.Now:dd MMM yyyy HH:mm}
  </p>

</body>
</html>";

            return html;
        }

        private string BuildSignalTable(List<TradeSignal> signals, string color)
        {
            if (signals.Count == 0)
                return "<p style='color:#aaa;'>None</p>";

            var rows = string.Join("", signals.Select(s => $@"
                <tr>
                  <td style='padding:8px; font-weight:bold;'>{s.Symbol}</td>
                  <td style='padding:8px;'>{s.StockName}</td>
                  <td style='padding:8px;'>{s.SectorName}</td>
                  <td style='padding:8px; color:{color};'>
                    {s.Pct1d:+0.00;-0.00}%
                  </td>
                  <td style='padding:8px;'>{s.Score:F3}</td>
                  <td style='padding:8px; color:#555; font-size:12px;'>
                    {s.Reason}
                  </td>
                </tr>"));

            return $@"
            <table style='width:100%; border-collapse:collapse;
                          border:1px solid #ddd;'>
              <tr style='background:#f5f5f5; font-weight:bold;'>
                <th style='padding:8px; text-align:left;'>Symbol</th>
                <th style='padding:8px; text-align:left;'>Name</th>
                <th style='padding:8px; text-align:left;'>Sector</th>
                <th style='padding:8px; text-align:left;'>1D%</th>
                <th style='padding:8px; text-align:left;'>Score</th>
                <th style='padding:8px; text-align:left;'>Reason</th>
              </tr>
              {rows}
            </table>";
        }
    }
}


